-
  name: 'Event callbacks'
  uriPattern: 'eventlistener/{@action}'
  defaults:
    '@package':    'Langeland.Huginn'
    '@controller': 'EventListener'
    '@format':     'json'


-
  name: 'Klipfolio endpoints'
  uriPattern: 'klipfolio/{@action}'
  defaults:
    '@package':    'Langeland.Huginn'
    '@controller': 'Klipfolio'
    '@format':     'json'

-
  name: 'Geckoboard endpoints'
  uriPattern: 'geckoboard/{@action}'
  defaults:
    '@package':    'Langeland.Huginn'
    '@controller': 'Geckoboard'
    '@format':     'json'


-
  name: 'Jira endpoints'
  uriPattern: 'devtools/checkbranch/{branchName}'
  defaults:
    '@package':    'Langeland.Huginn'
    '@controller': 'Jira'
    '@action':     'checkBranch'
    '@format':     'json'


