Langeland:
  Huginn:
    Teams:
      webapi:
        name: 'Team WebApi'
        Jira:
          board: 109
#          sprintMatch: '/^(Web-|)API Sprint [\w (+)]*/'
          sprintMatch: '/.*/'
        GitHub:
          tags:
            - 'team-web-api'
          teams:
            - 'team-web-api'
      display:
        name: 'Team Display'
        Jira:
          board: 57
#          sprintMatch: '/^Display Sprint [\w (+)]*/'
          sprintMatch: '/.*/'
        GitHub:
          tags:
            - 'team-display'
          teams:
            - 'team-display'

      core:
        name: 'Drupal Core'
        Jira:
          board: 67
          sprintMatch: '/^PF - Sprint [\w (+)]*/'
#          sprintMatch: '/.*/'
        GitHub:
          tags:
            - 'team-core'
          teams:
            - 'team-core'

    Jira:
      Api:
        endpoint: 'https://jiradrdk.atlassian.net'
        Authentication:
          user: ''
          password: ''

    GitHub:
      Api:
        endpoint: 'https://jiradrdk.atlassian.net'
        Authentication:
          authToken: ''


