Langeland:
  Huginn:
    Teams:
      webapi:
        name: 'Team WebApi'
        Jira:
          board: 109
          sprintMatch: '/.*/'
        GitHub:
          tags:
            - 'team-web-api'
          teams:
            - 'team-web-api'

      display:
        name: 'Team Display'
        Jira:
          board: 57
          sprintMatch: '/.*/'
        GitHub:
          tags:
            - 'team-display'
          teams:
            - 'team-display'

      core-pf:
        name: 'CorePF'
        Jira:
          board: 157
          sprintMatch: '/.*/'
        GitHub:
          tags:
          - 'team-core'
          teams:
          - 'team-core'

      core-rg:
        name: 'CoreRG'
        Jira:
          board: 102
          sprintMatch: '/.*/'
        GitHub:
          tags:
          teams:

      dev-ops:
        name: 'DevOps'
        Jira:
          board: 259
          sprintMatch: '/.*/'
        GitHub:
          tags:
          teams:
          - 'devops'

      aaa:
        name: 'AAA'
        Jira:
          board: 78
          sprintMatch: '/.*/'
        GitHub:
          tags:
          teams:
          - 'team-aaa'






#      core:
#        name: 'Drupal Core'
#        Jira:
#          board: 67
#          sprintMatch: '/.*/'
#        GitHub:
#          tags:
#            - 'team-core'
#          teams:
#            - 'team-core'

    Jira:
      Api:
        endpoint: 'https://jiradrdk.atlassian.net'
        Authentication:
          user: ''
          password: ''

    GitHub:
      Api:
        endpoint: 'https://jiradrdk.atlassian.net'
        Authentication:
          authToken: ''


